In [1]:
import pandas as pd
import numpy as np
import gc
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_mir_tcga = pd.read_parquet('/mnt/jack-5/amismailov/miRNA_study/PROPER_NORMALIZED_DATASETS/TCGA_miR_CPM_expanded.parquet')
df_mir_gtex = pd.read_parquet('/mnt/jack-5/amismailov/miRNA_study/PROPER_NORMALIZED_DATASETS/GTEx_adaptive_K/GTEx_CPM_boot.parquet')

In [6]:
df_mir_gtex = df_mir_gtex.T
df_mir_gtex.head()

,Adipose - Subcutaneous_0,Adipose - Subcutaneous_1,Adipose - Subcutaneous_2,Adipose - Subcutaneous_3,Adipose - Subcutaneous_4,Adipose - Subcutaneous_5,Adipose - Subcutaneous_6,Adipose - Subcutaneous_7,Adipose - Subcutaneous_8,Adipose - Subcutaneous_9,...,Whole Blood_793,Whole Blood_794,Whole Blood_795,Whole Blood_796,Whole Blood_797,Whole Blood_798,Whole Blood_799,Whole Blood_800,Whole Blood_801,Whole Blood_802
precursor,,,,,,,,,,,,,,,,,,,,,
hsa-mir-200b,0.662015,4.003702,0.723753,0.158902,1.206095,0.614309,1.467726,1.684485,6.532162,0.708417,...,2.021631,0.759081,0.088251,0.739770,0.243744,0.146135,0.000000,0.286833,0.156205,0.438832
hsa-mir-8-p1a,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
hsa-mir-200a,0.000000,3.401033,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.771795,0.000000,...,2.237994,1.534211,0.000000,0.000000,0.000000,0.000000,0.048981,0.000000,0.000000,3.922663
hsa-mir-8-p2a,5.087834,102.053673,12.063703,2.197923,22.024980,2.990791,3.633000,11.401424,25.755968,2.420718,...,48.809017,21.284156,3.219395,4.396965,2.894443,1.002507,2.522739,3.343095,4.044578,12.998962
hsa-mir-8-p3a,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [7]:
df_mir_tcga.head()

,0065bfd9-e1b9-43a8-9379-9658ba,01bf1906-9bdc-41c3-89a0-b89ef6,01d1ffca-4235-4dfe-bf62-56f71d,05387aad-2a1f-42c2-8d6f-950598,0630ecb0-b664-4e75-bb3c-fb62ee,079b5600-6afc-4785-bb22-48cfab,07c4bb93-a373-4748-a2c7-5806cb,08296da7-70ea-44df-8646-09f2cc,09659708-7747-4d59-a3b9-e221e0,0aef1fe8-ca61-4113-81d0-d82ee7,...,f6c215ea-5381-4521-bb61-be8e97,f9d6fb1b-988e-4d28-9272-cc672f,faadb553-9437-42cb-b469-498d67,fbb41c94-aabd-49cc-90b2-882c3e,fc0aa1e4-c1d8-43ed-a5cd-038f61,fd4edc52-09ef-4b01-be7c-f23f05,fe4b3b1c-9f7f-4109-8a76-ca1d6f,fe591474-99d7-44d3-be73-c3b8ed,fe83e13f-9754-403b-8f74-d6caf8,ffc76bfb-61f6-4492-a782-c23321
miRNA_ID,,,,,,,,,,,,,,,,,,,,,
hsa-let-7a-1,21899.594955,33161.484105,8462.889825,23176.542588,18393.592311,32792.981826,15850.882908,27868.728190,22906.938344,39210.382153,...,43487.267435,26584.567195,63122.382211,19317.653355,33354.841581,24926.549547,41441.740572,30414.813912,26748.424313,35156.613345
hsa-let-7a-2,21903.456892,32995.137123,8412.635821,23242.164454,18305.740642,33001.714984,15616.515950,27953.146253,22945.663387,38780.828305,...,43499.253918,26625.507756,63152.840985,19199.442982,33307.375104,24932.326981,41185.457568,30394.239034,26731.243812,35207.295346
hsa-let-7a-3,21945.696825,32955.896297,8386.642370,23363.422250,18260.627624,32770.650113,15809.592452,27921.274127,22814.428521,38646.252890,...,43553.039419,26625.879943,63255.258612,19377.732803,33497.241011,24849.131921,41227.227450,30686.348162,26796.735294,35424.929820
hsa-let-7b,8477.675230,17434.443294,2674.822320,28885.644931,6730.689739,26195.099875,8111.539287,17819.533134,16469.975722,23364.466925,...,21802.797768,12773.827220,66761.824953,12599.147326,37493.695859,9359.059095,21999.276461,48019.871001,9932.678869,80062.654878
hsa-let-7c,937.967883,3249.737577,547.980444,3513.622957,1599.893283,4963.565126,1849.734917,7870.261498,6734.930311,1923.476885,...,19912.006921,2626.150895,8836.471031,8957.358531,11688.990744,164.464309,1614.512131,14764.370267,11573.636948,15079.982160

In [8]:
lower_ = lambda x: x.lower()
df_mir_tcga.index = list(map(lower_, df_mir_tcga.index.tolist()))
df_mir_gtex.index = list(map(lower_, df_mir_gtex.index.tolist()))

In [9]:
gtex_names = df_mir_gtex.index.tolist()
tcga_names = df_mir_tcga.index.tolist()

In [10]:
print(f'GTEx miRs len: {len(gtex_names)}')
print(f'TCGA miRs len: {len(tcga_names)}')
print(f'Intersection: {len(set(gtex_names) & set(tcga_names))}')

GTEx miRs len: 606
TCGA miRs len: 1881
Intersection: 343

In [11]:
intersect = set(gtex_names) & set(tcga_names)
intersect = sorted(list(intersect))

In [12]:
len(intersect)

343

In [13]:
df_mir_tcga = df_mir_tcga.loc[intersect]
df_mir_gtex = df_mir_gtex.loc[intersect]

In [14]:
len(df_mir_tcga)

343

In [15]:
assert all(df_mir_tcga.index == df_mir_gtex.index)

In [16]:
pd_mir_merged = pd.concat([df_mir_tcga, df_mir_gtex], axis=1)
pd_mir_merged.shape

(343, 35580)

In [20]:
pd_mir_merged.sum(axis=0)

0065bfd9-e1b9-43a8-9379-9658ba    742480.990220
01bf1906-9bdc-41c3-89a0-b89ef6    609568.278398
01d1ffca-4235-4dfe-bf62-56f71d    751590.414078
05387aad-2a1f-42c2-8d6f-950598    615963.109914
0630ecb0-b664-4e75-bb3c-fb62ee    725828.325752
                                      ...
Whole Blood_798                   224599.789178
Whole Blood_799                   245469.705018
Whole Blood_800                   219019.895063
Whole Blood_801                   217791.546739
Whole Blood_802                   250640.555014
Length: 35580, dtype: float64

In [20]:
pd_mir_merged.to_parquet('/mnt/jack-5/amismailov/miRNA_study/PROPER_NORMALIZED_DATASETS/merged/merged_expanded_miR_v2.parquet')

In [21]:
del pd_mir_merged, df_mir_tcga, df_mir_gtex
gc.collect()

569907