In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

merged_rna = pd.read_parquet('/data/merged_rna_mature.parquet') # GTEx TCGA merged mature mRNA
merged_mir = pd.read_parquet('/data/merged_mir_mature.parquet') # GTEx TCGA merged mature miRNA

# this data will be used for split and training along with scRNA data

merged_rna = merged_rna.T
merged_mir = merged_mir.T

In [2]:
# check if the order of samples is the same
assert merged_rna.index.equals(merged_mir.index)

# Деление 85/15
X_BULK_TRAIN, X_BULK_TEST, Y_BULK_TRAIN, Y_BULK_TEST = train_test_split(
    merged_rna,
    merged_mir,
    test_size=0.15,
    random_state=42,
    shuffle=True
)

print(X_BULK_TRAIN.shape, X_BULK_TEST.shape)
print(Y_BULK_TRAIN.shape, Y_BULK_TEST.shape)

(30243, 17392) (5337, 17392)
(30243, 327) (5337, 327)

In [3]:
X_BULK_TRAIN

,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000286140,ENSG00000286190,ENSG00000286219,ENSG00000286224,ENSG00000286237,ENSG00000286264,ENSG00000286522,ENSG00000286920,ENSG00000287080,ENSG00000287585
TCGA-93-8067-01A,32.093442,0.000000,13.266098,3.231369,0.476167,4.103878,7.135750,30.678516,28.954841,19.170626,...,0.0,5.106043,0.042997,0.000000,0.002934,0.554890,4.477127,0.000000,0.495519,0.000000
Esophagus - Muscularis_84,11.565598,0.422785,6.010158,1.884133,0.151282,2.431516,10.578552,8.986692,1.907846,4.250138,...,0.0,22.468016,0.425388,1.697727,0.000000,1.824022,0.000000,0.000000,0.000000,0.000000
Esophagus - Mucosa_503,25.368385,0.000000,7.577287,2.510693,0.218128,1.491141,3.675775,6.181528,2.073851,6.077749,...,0.0,10.008772,0.312140,1.168627,0.003873,2.275707,0.311024,0.000000,0.981070,0.000000
Thyroid_596,23.193277,0.010804,8.744948,3.675459,0.222103,6.137447,29.688567,16.268171,2.349364,16.575857,...,0.0,121.246356,0.550929,0.000000,0.039362,4.785153,0.000000,0.114314,0.332357,0.000000
Skin - Not Sun Exposed (Suprapubic)_59,4.305202,0.454957,6.701360,2.276586,0.113359,1.382159,3.377553,1.973938,1.656646,4.956205,...,0.0,76.299056,0.890928,0.574848,0.011431,2.277442,0.000000,0.041496,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Adipose - Visceral (Omentum)_172,13.962369,0.997073,6.119597,0.893746,0.125652,30.018949,5.428629,10.651939,2.033291,4.792782,...,0.0,12.489761,0.183545,0.000000,0.000000,0.557568,0.000000,0.000000,0.000000,0.000000
TCGA-BH-A0DH-01A,23.182999,0.223572,9.276162,3.993615,0.489279,2.152664,1.985016,18.071251,4.737024,13.878651,...,0.0,2.980859,0.076700,0.000000,0.000000,0.200036,6.243602,0.000000,4.376517,0.000000
TCGA-43-6770-01A,92.490971,0.018976,24.206610,2.951701,0.786041,10.984635,5.621872,16.356548,35.418383,14.041171,...,0.0,7.002556,0.041918,0.000000,0.000000,0.653671,4.163796,0.000000,4.961714,0.225153
fbb41c94-aabd-49cc-90b2-882c3e,32.338078,0.027296,10.240078,2.493993,0.299543,0.920259,4.337078,7.975727,1.064275,6.600834,...,0.0,4.778085,0.072859,0.000000,0.004972,0.940263,1.197870,0.000000,0.000000,0.000000
TCGA-FL-A1YM-11A,56.401320,0.028392,7.776543,2.728777,0.131649,4.966656,4.850460,15.144007,2.962665,6.541673,...,0.0,112.830997,0.041812,0.000000,0.000000,3.772352,0.000000,0.000000,0.000000,0.000000

In [4]:
Y_BULK_TRAIN

,hsa-let-7a-2-3p,hsa-let-7a-3p,hsa-let-7a-5p,hsa-let-7b-5p,hsa-let-7c-3p,hsa-let-7c-5p,hsa-let-7d-5p,hsa-let-7e-3p,hsa-let-7e-5p,hsa-let-7f-5p,...,hsa-mir-92a-1-5p,hsa-mir-92a-3p,hsa-mir-92b-3p,hsa-mir-93-5p,hsa-mir-95-3p,hsa-mir-96-5p,hsa-mir-98-5p,hsa-mir-99a-5p,hsa-mir-99b-3p,hsa-mir-99b-5p
TCGA-93-8067-01A,23.606543,22.533519,11413.763688,12418.114803,11.803272,800.476423,247.868705,32.190741,1130.968029,2819.908900,...,5.365123,21933.697804,481.788088,7347.000091,5.365123,35.409815,40.774938,417.406607,216.750989,94348.915440
Esophagus - Muscularis_84,2.569607,303.512559,0.000000,26778.227759,3.676431,0.000000,4376.823234,52.967190,490.912507,0.000000,...,40.407196,6165.056900,1076.039289,1120.615561,448.973342,0.833959,2876.851059,82075.537616,656.685081,15440.857218
Esophagus - Mucosa_503,1.984013,326.970043,0.000000,39728.739964,9.298667,0.000000,3298.589058,23.795281,342.277920,0.000000,...,87.585693,17497.884919,464.547955,1637.927800,751.927930,112.737842,2119.392025,190723.531412,359.137874,5916.508913
Thyroid_596,1.927976,255.697004,0.000000,13605.205090,4.353320,0.000000,2247.587361,24.479953,153.854563,0.000000,...,47.243145,5798.742785,432.662857,557.320976,1251.345602,96.751416,1687.608037,239075.801672,262.576712,6946.594317
Skin - Not Sun Exposed (Suprapubic)_59,0.624857,201.802165,0.000000,59591.719538,4.220506,0.000000,1961.247114,14.354002,148.615115,0.000000,...,57.807716,12025.185100,308.443270,809.664499,508.400478,143.203795,1956.436039,222816.736882,183.962950,3609.488211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Adipose - Visceral (Omentum)_172,2.034685,446.170174,0.000000,36074.219358,11.290401,0.000000,2316.364560,30.890432,229.348219,0.000000,...,17.148582,10065.061284,449.020864,780.061643,745.813105,8.541633,2672.792764,240883.592328,398.845458,8267.354841
TCGA-BH-A0DH-01A,3.553893,58.893084,33920.385689,61411.271222,19.292562,1396.172254,220.849066,22.338756,1348.448548,4248.932944,...,0.507699,2737.513016,175.156156,4167.193404,4.569291,62.954676,115.755372,513.283691,107.124489,51876.176275
TCGA-43-6770-01A,6.981461,27.227697,70427.579562,34491.906742,72.607192,7267.700621,264.597362,13.962921,2218.708220,36875.377435,...,6.981461,27751.306406,88.664551,9084.974849,0.000000,21.642528,160.573597,684.183152,66.323877,27759.684159
fbb41c94-aabd-49cc-90b2-882c3e,4.342648,70.025198,96693.942115,20966.304309,21.713240,14950.108403,6655.650816,67.853874,9645.021100,36749.115457,...,26.598719,43290.771765,11097.636840,3966.466073,20.627578,5.971141,2593.103658,2720.126110,280.643624,27695.237309
TCGA-FL-A1YM-11A,32.262173,77.089612,93826.718173,51346.096702,154.518827,15909.496116,1246.508469,62.316933,1780.192724,17989.727045,...,10.357855,10553.126459,82.523241,2368.892474,1.698009,8.659846,106.804771,20788.725220,49.242263,117801.248037

In [ ]:
import Path
here = Path(__file__).resolve().parent
workdir = here.parent
train_dir = workdir / 'ml_pipeline/data/bulk_TRAIN'

X_BULK_TRAIN.to_parquet(train_dir / 'X_BULK_TRAIN.parquet')
Y_BULK_TRAIN.to_parquet(train_dir / 'Y_BULK_TRAIN.parquet')

In [ ]:
test_dir = workdir / 'ml_pipeline/data/bulk_TEST'
X_BULK_TEST.to_parquet(test_dir / 'X_BULK_TEST.parquet')
Y_BULK_TEST.to_parquet(test_dir / 'Y_BULK_TEST.parquet')